### ISSUE TITLE
Optical flow randomly fails when cropping

### ISSUE THREAD

**Issue by castim** [NVIDIA/DALI#2815]
I recently upgraded from 0.23.0 to 0.31.0 (cuda 10). When running the following code

```python
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import sys
from pathlib import Path

video_filename = Path(sys.argv[1])
if not video_filename.exists():
    raise FileNotFoundError(f"{video_filename}")


class OFPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(OFPipeline, self).__init__(batch_size, num_threads, device_id, seed=16)
        self.input = ops.VideoReader(device="gpu", filenames=video_filename, sequence_length=sequence_length)
        self.crop = ops.Crop(device="gpu", crop=[256,256])
        self.of_op = ops.OpticalFlow(device="gpu", output_format=4)
    def define_graph(self):
        seq = self.input(name="Reader")
        seq = self.crop(seq)
        of = self.of_op(seq)
        return seq, of
    
sequence_length = 10
pipe = OFPipeline(batch_size=1, num_threads=1, device_id=0)

pipe.build()
for i in range(10):
    pipe_out = pipe.run()
    flow_vector = pipe_out[0].as_cpu().as_array()
    print(flow_vector.shape)
    print(flow_vector)
```

I randomly (more than half of the time) encounter the following error:

```
python vbt.py ../data/test_videos/good.mp4
Traceback (most recent call last):
File "vbt.py", line 33, in <module>
pipe_out = pipe.run()
File "/usr/local/lib64/python3.6/site-packages/nvidia/dali/pipeline.py", line 747, in run
return self.outputs()
File "/usr/local/lib64/python3.6/site-packages/nvidia/dali/pipeline.py", line 646, in outputs
return self._outputs()
File "/usr/local/lib64/python3.6/site-packages/nvidia/dali/pipeline.py", line 730, in _outputs
return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:  
Error when executing GPU operator OpticalFlow encountered:
[/opt/dali/dali/operators/sequence/optical_flow/turing_of/optical_flow_turing.cc:33] Optical flow failed, code: 5
Stacktrace (14 entries): 
[frame 0]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x40e18e) [0x7fabb520618e]
[frame 1]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali_operators.so(dali::optical_flow::OpticalFlowTuring::OpticalFlowTuring(dali::optical_flow::OpticalFlowParams, unsigned long, unsigned long, unsigned long, dali::DALIImageType, int, CUstream_st*)+0x13f4) [0x7fabb7200704]
[frame 2]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x240ceb4) [0x7fabb7204eb4]
[frame 3]: /usr/lib64/libpthread.so.0(+0x620b) [0x7fabda63a20b]
[frame 4]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x240d7d8) [0x7fabb72057d8]
[frame 5]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x240bf15) [0x7fabb7203f15]
[frame 6]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x424f04) [0x7fabb521cf04]
[frame 7]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali.so(void dali::Executor<dali::AOT_WS_Policy<dali::UniformQueuePolicy>, dali::UniformQueuePolicy>::RunHelper<dali::DeviceWorkspace>(dali::OpNode&, dali::DeviceWorkspace&)+0x5ce) [0x7fabb401be4e]
[frame 8]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali.so(dali::Executor<dali::AOT_WS_Policy<dali::UniformQueuePolicy>, dali::UniformQueuePolicy>::RunGPU()+0x3dc) [0x7fabb401ce6c]
[frame 9]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali.so(+0xbbe98) [0x7fabb3fcee98]
[frame 10]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali.so(+0x13998c) [0x7fabb404c98c]
[frame 11]: /usr/local/lib64/python3.6/site-packages/nvidia/dali/libdali.so(+0x8b01ff) [0x7fabb47c31ff]
[frame 12]: /usr/lib64/libpthread.so.0(+0x7ea5) [0x7fabda63bea5]
[frame 13]: /usr/lib64/libc.so.6(clone+0x6d) [0x7fabd9c5b96d]
Current pipeline object is no longer valid.
```

It sometimes works just fine.
I do not encounter this error when using DALI version 0.23.0. I also do not encounter this error if I remove the crop operation.

Do you have an idea of what might be wrong?

**Comment by JanuszL** [comment]
Hi,
It seems that there is a regression between 0.28 and 0.29. Let us narrow it down and get back to you.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2816 should fix the problem.
Please check the nightly build that follows its merge.

**Comment by castim** [comment]
Thank you for your quick reaction!
I tried the nightly build nvidia-dali-nightly-cuda100==1.1.0.dev20210325 and I still have the problem. Is it not included in the build yet?

**Comment by JanuszL** [comment]
The next one after 2021/03/25 should have it,

**Comment by castim** [comment]
I think I have the last one, ok, waiting for it then =) Do you know when it will be available?

**Comment by JanuszL** [comment]
@castim -we publish them daily (except for weekends, when the weekly build is run) unless the CI set of tests fails. I guess one should be available today/tomorrow.

**Comment by castim** [comment]
Thanks, it works with nvidia-dali-nightly-cuda100==1.1.0.dev20210329
