### ISSUE TITLE
can not run "from nvidia.dali.pipeline import Pipeline" 

### ISSUE THREAD

**Issue by xxradon** [NVIDIA/DALI#5]
when I use the 3.1. Binary Installation  step [In]( https://docs.nvidia.com/deeplearning/sdk/dali-install-guide/index.html ,everything is ok.But when I 'get started',in python ,run this command" from nvidia.dali.pipeline import Pipeline",I got this error:'ImportError: libdali.so: cannot open shared object file: No such file or directory
'

**Comment by JanuszL** [comment]
Hi,
Could you tell us which python version do you use?
Can you check status of following command:
pip show nvidia-dali
_grab the path from Location:_
ls _LOCATION_/nvidia/dali/.libs/

**Comment by cliffwoolley** [comment]
I found an error in the RPATH updating in bundle-wheel.sh that likely accounts for this.  I have a fix pending.

**Comment by cliffwoolley** [comment]
(It would still help to know the answers to @JanuszL 's questions so that I can attempt to reproduce the problem.  Further: are you using virtualenv or Conda environments or any similar setup?)

**Comment by JiangPQ** [comment]
Hi, I got a similar problem. Here is the traceback:

> Traceback (most recent call last):
  File "/home/xxxxx/PycharmProjects/torch90/111.py", line 500, in <module>
    from nvidia.dali.pipeline import Pipeline
  File "/home/xxxxx/miniconda3/envs/torch90/lib/python3.6/site-packages/nvidia/dali/__init__.py", line 17, in <module>
    from . import ops
  File "/home/xxxxx/miniconda3/envs/torch90/lib/python3.6/site-packages/nvidia/dali/ops.py", line 19, in <module>
    from nvidia.dali import backend as b
  File "/home/xxxxx/miniconda3/envs/torch90/lib/python3.6/site-packages/nvidia/dali/backend.py", line 15, in <module>
    from nvidia.dali.backend_impl import *
ImportError: libnppicom.so.9.0: cannot open shared object file: No such file or directory

Everything goes fine when I run pytorch so i think CUDA9.0 is properly installed.
I use conda environment BTW @cliffwoolley

**Comment by xxradon** [comment]
@JanuszL @cliffwoolley 
I also use conda environment  and this is what pip show nvidia-dali gives:
`Name: nvidia-dali
Version: 0.1.1
Summary: NVIDIA DALI
Home-page: https://github.com/NVIDIA/dali
Author: NVIDIA Corporation
Author-email: UNKNOWN
License: Apache License 2.0
Location: /home/shining/ProgramFiles/miniconda/envs/pytorch/lib/python3.6/site-packages
Requires: future
`
I have search  libdali.so in my conda env ,I found nothing.But when I compiled from DALI source,I got the libdali.so.
And @JiangPQ,I think your cuda environment got something wrong,you can test your pytorch cuda to verify.

**Comment by JanuszL** [comment]
@xxradon 
Could you also:
ls /home/shining/ProgramFiles/miniconda/envs/pytorch/lib/python3.6/site-packages/nvidia/dali/.libs/ ?

**Comment by cliffwoolley** [comment]
It's not called libdali.so in the installed binary package; it's libdali-*.so, where the * is a hash.  Bundle-wheel.sh renames it when packaging the wheel.  But because of some path errors, not all references to it are corrected properly.  I have a fix for that, but the fix exposes another error that I'm still trying to sort out.

**Comment by xxradon** [comment]
I have test recent release editon,this problem has been fixed.Thank you.

**Comment by cliffwoolley** [comment]
Actually this isn't fixed yet.  :)  Glad it worked for you regardless, but I'm reopening this until I push the proper fix.
